flaky artifact

diff --git a/.github/workflows/ci_pull_request_open.yml b/.github/workflows/ci_pull_request_open.yml
--- a/.github/workflows/ci_pull_request_open.yml
+++ b/.github/workflows/ci_pull_request_open.yml
@@ -2,7 +2,7 @@ name: CI Pull Request Open
 on:
   pull_request:
 jobs:
-  image:
+  ci-build-test-pr:
     runs-on: ubuntu-latest
     env:
       MAVEN_OPTS: "-Xmx1500m -XX:+HeapDumpOnOutOfMemoryError"
@@ -35,24 +35,28 @@ jobs:
             mvn -s maven-settings.xml verify -B -e -DrerunFailingTestsCount=2
             -Dmaven.test.failure.ignore=true -Dansi.strip=true
             -pl :infinispan-component-annotations,:infinispan-logging-annotations,:infinispan-checkstyle,commons,:infinispan-defaults-maven-plugin,:infinispan-logging-processor,:infinispan-commons-spi,:infinispan-component-processor,:infinispan-commons-test,:infinispan-api,:infinispan-commons
-      - name: Publish Test Report
-        if: success() || failure()
-        uses: ScaCap/action-surefire-report@v1
-      - name: Install xmlstarlet tool
-        if: success() || failure()
-        shell: bash
-        run: |
-            sudo apt-get update
-            sudo apt-get install -y xmlstarlet
-      - name: Publish Flaky Tests
-        if: success() || failure()
-        env:
-          TOKEN: ${{ secrets.JIRA_API_TOKEN }}
-          RUNNER_DEBUG: 1
-          FLAKY_TEST_GLOB: "**/target/*-reports*/**/TEST-*FLAKY.xml"
-          PROJECT_KEY: "ISPN"
-          TYPE: "Bug"
-          JENKINS_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          TARGET_BRANCH: ${{ github.base_ref }}
-        run: bin/jira/track_flaky_tests.sh
-
+      - name: Archive code coverage results
+        uses: actions/upload-artifact@v4
+        with:
+          name: flaky-test-report
+          path: "**/target/*-reports*/**/TEST-*FLAKY.xml"
+#      - name: Publish Test Report
+#        if: success() || failure()
+#        uses: ScaCap/action-surefire-report@v1
+#      - name: Install xmlstarlet tool
+#        if: success() || failure()
+#        shell: bash
+#        run: |
+#            sudo apt-get update
+#            sudo apt-get install -y xmlstarlet
+#      - name: Publish Flaky Tests
+#        if: success() || failure()
+#        env:
+#          TOKEN: ${{ secrets.JIRA_API_TOKEN }}
+#          RUNNER_DEBUG: 1
+#          FLAKY_TEST_GLOB: "**/target/*-reports*/**/TEST-*FLAKY.xml"
+#          PROJECT_KEY: "ISPN"
+#          TYPE: "Bug"
+#          JENKINS_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+#          TARGET_BRANCH: ${{ github.base_ref }}
+#        run: bin/jira/track_flaky_tests.sh
