test create image

diff --git a/.github/workflows/on_propen_push_do_test.yml b/.github/workflows/on_propen_push_do_test.yml
--- a/.github/workflows/on_propen_push_do_test.yml
+++ b/.github/workflows/on_propen_push_do_test.yml
@@ -51,66 +51,66 @@ jobs:
           path: |
             distribution/target/distribution/infinispan-server-*.zip
 
-      - name: Maven Test
-        run: >
-            ./mvnw verify -s maven-settings.xml -B -e -DrerunFailingTestsCount=2
-            -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative
-
-      - name: Archive commit sha PR
-        if: >
-          (success() || failure()) &&
-          github.event_name == 'pull_request'
-        run: |
-           echo -n ${{ github.event.pull_request.head.sha }} > github-sha.txt
-
-      - name: Archive commit sha push
-        if: >
-          (success() || failure()) &&
-          github.event_name == 'push'
-        run: |
-           echo -n $GITHUB_SHA > github-sha.txt
-
-      - name: Archive surefire test report
-        if: (success() || failure())
-        uses: actions/upload-artifact@v4
-        with:
-          name: surefire-test-report
-          path: |
-            **/surefire-reports/TEST-*.xml
-            **/*.dump*
-            **/hs_err_*
-            github-sha.txt
-            !**/target/*-reports*/**/TEST-*FLAKY.xml
-
-# Create artifact with branch name and surefile flaky test report
-      - name: Check flaky report existence
-        if: success() || failure()
-        id: check_flaky_report
-        uses: andstor/file-existence-action@v3
-        with:
-          files: "**/target/*-reports*/**/TEST-*FLAKY.xml"
-
-      - name: Archive base_ref
-        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
-        env:
-          TARGET_BRANCH: ${{ github.base_ref }}
-          EVENT_NAME: ${{ github.event_name }}
-          EVENT_NUMBER: ${{ github.event.number }}
-        run: |
-          echo -n $TARGET_BRANCH > target-branch.txt
-          echo -n $EVENT_NAME > event-name.txt
-          echo -n $EVENT_NUMBER > event-number.txt
-
-      - name: Archive flaky test report
-        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
-        uses: actions/upload-artifact@v4
-        with:
-          name: flaky-test-report
-          path: |
-            **/target/*-reports*/**/TEST-*FLAKY.xml
-            target-branch.txt
-            event_name.txt
-            event_number.txt
+#      - name: Maven Test
+#        run: >
+#            ./mvnw verify -s maven-settings.xml -B -e -DrerunFailingTestsCount=2
+#            -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative
+#
+#      - name: Archive commit sha PR
+#        if: >
+#          (success() || failure()) &&
+#          github.event_name == 'pull_request'
+#        run: |
+#           echo -n ${{ github.event.pull_request.head.sha }} > github-sha.txt
+#
+#      - name: Archive commit sha push
+#        if: >
+#          (success() || failure()) &&
+#          github.event_name == 'push'
+#        run: |
+#           echo -n $GITHUB_SHA > github-sha.txt
+#
+#      - name: Archive surefire test report
+#        if: (success() || failure())
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: surefire-test-report
+#          path: |
+#            **/surefire-reports/TEST-*.xml
+#            **/*.dump*
+#            **/hs_err_*
+#            github-sha.txt
+#            !**/target/*-reports*/**/TEST-*FLAKY.xml
+#
+## Create artifact with branch name and surefile flaky test report
+#      - name: Check flaky report existence
+#        if: success() || failure()
+#        id: check_flaky_report
+#        uses: andstor/file-existence-action@v3
+#        with:
+#          files: "**/target/*-reports*/**/TEST-*FLAKY.xml"
+#
+#      - name: Archive base_ref
+#        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
+#        env:
+#          TARGET_BRANCH: ${{ github.base_ref }}
+#          EVENT_NAME: ${{ github.event_name }}
+#          EVENT_NUMBER: ${{ github.event.number }}
+#        run: |
+#          echo -n $TARGET_BRANCH > target-branch.txt
+#          echo -n $EVENT_NAME > event-name.txt
+#          echo -n $EVENT_NUMBER > event-number.txt
+#
+#      - name: Archive flaky test report
+#        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: flaky-test-report
+#          path: |
+#            **/target/*-reports*/**/TEST-*FLAKY.xml
+#            target-branch.txt
+#            event_name.txt
+#            event_number.txt
   images-branch:
     if: github.event_name == 'push'
     needs: ci-build-test-pr
@@ -119,8 +119,7 @@ jobs:
     with:
       repository: ${{ github.repository }}
       run-id: ${{ github.run_id }}
-      name: ${{ needs.ci-build-test-pr.outputs.server-distro-name-branch }}
-      art-name: ${{ needs.ci-build-test-pr.outputs.server-distro-name-branch }}
+      art-name: infinispan-server
       tags: quay.io/infinispan-test/server:gh-${{ github.event.base_ref }}
   images-pr:
     if: github.event_name == 'pull_request'
@@ -130,6 +129,5 @@ jobs:
     with:
       repository: ${{ github.repository }}
       run-id: ${{ github.run_id }}
-      name: ${{ needs.ci-build-test-pr.outputs.server-distro-name-branch }}
-      art-name: ${{ needs.ci-build-test-pr.outputs.server-distro-name-pr }}
-      tags: quay.io/infinispan-test/server:${{ github.event.pull_request.number }}
+      art-name: infinispan-server
+      tags: quay.io/infinispan-test/server:gh-${{ github.event.pull_request.number }}
